spring.config.import=optional:file:.env[.properties]

spring.application.name=platinum-bench
spring.datasource.url=jdbc:postgresql://localhost:5432/platinum_bench
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

